stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps: 
    - src/data_ingestion.py
    outs: 
    - data/clean_data
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/clean_data
    - src/data_preprocessing.py

    outs:
    - data/interim
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/interim
    - src/model_building.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    outs:
    - reports/metrics.json